export const COUNTRIES: Record<string, string> = {
  Afghanistan: "afghanistan.csv",
  Angola: "angola.csv",
  Albania: "albania.csv",
  Andorra: "andorra.csv",
  "Antigua and Barbuda": "antigua_and_barbuda.csv",
  Algeria: "algeria.csv",
  Anguilla: "anguilla.csv",
  Argentina: "argentina.csv",
  Armenia: "armenia.csv",
  Aruba: "aruba.csv",
  Australia: "australia.csv",
  Austria: "austria.csv",
  Azerbaijan: "azerbaijan.csv",
  Bahamas: "bahamas.csv",
  Bahrain: "bahrain.csv",
  Bangladesh: "bangladesh.csv",
  Barbados: "barbados.csv",
  Belarus: "belarus.csv",
  Belgium: "belgium.csv",
  Belize: "belize.csv",
  Benin: "benin.csv",
  Bermuda: "bermuda.csv",
  Bhutan: "bhutan.csv",
  Bolivia: "bolivia.csv",
  "Bosnia and Herzegovina": "bosnia_and_herzegovina.csv",
  Brazil: "brazil.csv",
  "British Virgin Islands": "british_virgin_islands.csv",
  "Brunei Darussalam": "brunei_darussalam.csv",
  Bulgaria: "bulgaria.csv",
  "Burkina Faso": "burkina_faso.csv",
  Cambodia: "cambodia.csv",
  Cameroon: "cameroon.csv",
  Canada: "canada.csv",
  "Cape Verde": "cape_verde.csv",
  "Cases on an international conveyance Japan": "cases_on_an_international_conveyance_japan.csv",
  "Cayman Islands": "cayman_islands.csv",
  "Central African Republic": "central_african_republic.csv",
  Chad: "chad.csv",
  Chile: "chile.csv",
  China: "china.csv",
  Colombia: "colombia.csv",
  Congo: "congo.csv",
  "Costa Rica": "costa_rica.csv",
  "Cote dIvoire": "cote_divoire.csv",
  Croatia: "croatia.csv",
  Cuba: "cuba.csv",
  Curaçao: "curaçao.csv",
  Cyprus: "cyprus.csv",
  "Czech Republic": "czech_republic.csv",
  "Democratic Republic of the Congo": "democratic_republic_of_the_congo.csv",
  Denmark: "denmark.csv",
  Djibouti: "djibouti.csv",
  Dominica: "dominica.csv",
  "Dominican Republic": "dominican_republic.csv",
  Ecuador: "ecuador.csv",
  Egypt: "egypt.csv",
  "El Salvador": "el_salvador.csv",
  "Equatorial Guinea": "equatorial_guinea.csv",
  Eritrea: "eritrea.csv",
  Estonia: "estonia.csv",
  Eswatini: "eswatini.csv",
  Ethiopia: "ethiopia.csv",
  "Faroe Islands": "faroe_islands.csv",
  Fiji: "fiji.csv",
  Finland: "finland.csv",
  France: "france.csv",
  "French Polynesia": "french_polynesia.csv",
  Gabon: "gabon.csv",
  Gambia: "gambia.csv",
  Georgia: "georgia.csv",
  Germany: "germany.csv",
  Ghana: "ghana.csv",
  Gibraltar: "gibraltar.csv",
  Greece: "greece.csv",
  Greenland: "greenland.csv",
  Grenada: "grenada.csv",
  Guam: "guam.csv",
  Guatemala: "guatemala.csv",
  Guernsey: "guernsey.csv",
  Guinea: "guinea.csv",
  "Guinea Bissau": "guinea_bissau.csv",
  Guyana: "guyana.csv",
  Haiti: "haiti.csv",
  "Holy See": "holy_see.csv",
  Honduras: "honduras.csv",
  Hungary: "hungary.csv",
  Iceland: "iceland.csv",
  India: "india.csv",
  Indonesia: "indonesia.csv",
  Iran: "iran.csv",
  Iraq: "iraq.csv",
  Ireland: "ireland.csv",
  "Isle of Man": "isle_of_man.csv",
  Israel: "israel.csv",
  Italy: "italy.csv",
  Jamaica: "jamaica.csv",
  Japan: "japan.csv",
  Jersey: "jersey.csv",
  Jordan: "jordan.csv",
  Kazakhstan: "kazakhstan.csv",
  Kenya: "kenya.csv",
  Kosovo: "kosovo.csv",
  Kuwait: "kuwait.csv",
  Kyrgyzstan: "kyrgyzstan.csv",
  Laos: "laos.csv",
  Latvia: "latvia.csv",
  Lebanon: "lebanon.csv",
  Liberia: "liberia.csv",
  Libya: "libya.csv",
  Liechtenstein: "liechtenstein.csv",
  Lithuania: "lithuania.csv",
  Luxembourg: "luxembourg.csv",
  Madagascar: "madagascar.csv",
  Malaysia: "malaysia.csv",
  Maldives: "maldives.csv",
  Mali: "mali.csv",
  Malta: "malta.csv",
  Mauritania: "mauritania.csv",
  Mauritius: "mauritius.csv",
  Mexico: "mexico.csv",
  Moldova: "moldova.csv",
  Monaco: "monaco.csv",
  Mongolia: "mongolia.csv",
  Montenegro: "montenegro.csv",
  Montserrat: "montserrat.csv",
  Morocco: "morocco.csv",
  Mozambique: "mozambique.csv",
  Myanmar: "myanmar.csv",
  Namibia: "namibia.csv",
  Nepal: "nepal.csv",
  Netherlands: "netherlands.csv",
  "New Caledonia": "new_caledonia.csv",
  "New Zealand": "new_zealand.csv",
  Nicaragua: "nicaragua.csv",
  Niger: "niger.csv",
  Nigeria: "nigeria.csv",
  "North Macedonia": "north_macedonia.csv",
  Norway: "norway.csv",
  Oman: "oman.csv",
  Pakistan: "pakistan.csv",
  Palestine: "palestine.csv",
  Panama: "panama.csv",
  "Papua New Guinea": "papua_new_guinea.csv",
  Paraguay: "paraguay.csv",
  Peru: "peru.csv",
  Philippines: "philippines.csv",
  Poland: "poland.csv",
  Portugal: "portugal.csv",
  "Puerto Rico": "puerto_rico.csv",
  Qatar: "qatar.csv",
  Romania: "romania.csv",
  Russia: "russia.csv",
  Rwanda: "rwanda.csv",
  "Saint Kitts and Nevis": "saint_kitts_and_nevis.csv",
  "Saint Lucia": "saint_lucia.csv",
  "Saint Vincent and the Grenadines": "saint_vincent_and_the_grenadines.csv",
  "San Marino": "san_marino.csv",
  "Saudi Arabia": "saudi_arabia.csv",
  Senegal: "senegal.csv",
  Serbia: "serbia.csv",
  Seychelles: "seychelles.csv",
  Singapore: "singapore.csv",
  "Sint Maarten": "sint_maarten.csv",
  Slovakia: "slovakia.csv",
  Slovenia: "slovenia.csv",
  Somalia: "somalia.csv",
  "South Africa": "south_africa.csv",
  "South Korea": "south_korea.csv",
  Spain: "spain.csv",
  "Sri Lanka": "sri_lanka.csv",
  Sudan: "sudan.csv",
  Suriname: "suriname.csv",
  Sweden: "sweden.csv",
  Switzerland: "switzerland.csv",
  Syria: "syria.csv",
  Taiwan: "taiwan.csv",
  Thailand: "thailand.csv",
  "Timor Leste": "timor_leste.csv",
  Togo: "togo.csv",
  "Trinidad and Tobago": "trinidad_and_tobago.csv",
  Tunisia: "tunisia.csv",
  Turkey: "turkey.csv",
  "Turks and Caicos islands": "turks_and_caicos_islands.csv",
  Uganda: "uganda.csv",
  Ukraine: "ukraine.csv",
  "United Arab Emirates": "united_arab_emirates.csv",
  "United Kingdom": "united_kingdom.csv",
  "United Republic of Tanzania": "united_republic_of_tanzania.csv",
  "United States of America": "united_states_of_america.csv",
  "United States Virgin Islands": "united_states_virgin_islands.csv",
  Uruguay: "uruguay.csv",
  Uzbekistan: "uzbekistan.csv",
  Venezuela: "venezuela.csv",
  Vietnam: "vietnam.csv",
  Zambia: "zambia.csv",
  Zimbabwe: "zimbabwe.csv",
};
